apiVersion: v1
kind: Service
metadata:
  name: deploy-stuff-service
spec:
  selector:
    app: deploy-stuff
  ports:
    - port: {{ if eq .Values.ENV "PR" }} 3001 {{else}} 3000 {{end}}
      targetPort: {{ if eq .Values.ENV "PR" }} 3001 {{else}} 3000 {{end}}
  type: LoadBalancer